apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::767397791112:role/GitHubActionsEKSRole
      username: github-actions
      groups:
        - system:masters
