apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-cluster                   # 클러스터 이름
  region: ap-northeast-2                # 리전 (서울 리전)
  version: "1.27"                       # Kubernetes 버전

vpc:
  subnets:
    private:
      ap-northeast-2a: { id: subnet-06737ff6973e505e3 } # 프라이빗 서브넷
      ap-northeast-2c: { id: subnet-0dd4ba475138eb206 }
    public:
      ap-northeast-2a: { id: subnet-0b8a04d79f6c7d6ff } # 퍼블릭 서브넷
      ap-northeast-2c: { id: subnet-0f1a6096656e5afeb }

nodeGroups:
  - name: worker-nodes
    instanceType: t3.medium
    desiredCapacity: 3                   # 기본 노드 수
    minSize: 1                           # 최소 노드 수
    maxSize: 3                           # 최대 노드 수
    privateNetworking: true              # 프라이빗 서브넷에서 실행
    ###########
    #userData: |
      # #!/bin/bash