apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: my-cluster                # 클러스터 이름
  region: ap-northeast-2                # 클러스터가 위치할 AWS 리전
  version: "1.27"                    # Kubernetes 버전
vpc:
  subnets:
    private:
      ap-northeast-2a:
        id: subnet-06737ff6973e505e3 # 프라이빗 서브넷 ID
      ap-northeast-2c:
        id: subnet-0dd4ba475138eb206
    public:
      ap-northeast-2a:
        id: subnet-0b8a04d79f6c7d6ff # 퍼블릭 서브넷 ID
      ap-northeast-2c:
        id: subnet-0f1a6096656e5afeb

iam:
  withOIDC: true       # OIDC 활성화

managedNodeGroups:
  - name: worker-nodes              # 노드 그룹 이름
    instanceType: t3.medium         # EC2 인스턴스 유형
    desiredCapacity: 4              # 원하는 노드 수
    minSize: 2                      # 최소 노드 수
    maxSize: 5                      # 최대 노드 수
    volumeSize: 20                  # 노드 디스크 크기 (GiB)
    privateNetworking: true         # 프라이빗 서브넷만 사용
    volumetype: gp3                 # 디스크 유형
    iam:
      withAddonPolicies:   
        awsLoadBalancerController: true  # ALB 컨트롤러 정책 활성화
        autoScaler: true             # AutoScaler 정책 활성화
        cloudWatch: true             # CloudWatch 접근 권한
        ebs: true
        albIngress: true
      attachPolicy:                  # 추가 정책
        Version: "2012-10-17"
        Statement:
          - Sid: "Statement1"
            Effect: "Allow"
            Action:
              - "ec2:CreateVolume"
              - "ec2:DeleteVolume"
              - "ec2:DescribeVolumes"
              - "ec2:AttachVolume"
              - "ec2:DetachVolume"
              - "ec2:ModifyVolume"
              - "ec2:DescribeTags"
              - "ec2:CreateTags"
              - "ec2:DeleteTags"
            Resource: "*"
    ssh:
      allow: true   # SSH 허용 여부
      publicKeyName: my-key  # AWS에 등록한 키 페어 이
    preBootstrapCommands:           # 사용자 정의 명령어 실행
    - echo "p@ssw0rd" | passwd root --stdin
    - sed -i "s/^#PermitRootLogin.*/PermitRootLogin yes/" /etc/ssh/sshd_config
    - sed -i "s/^PasswordAuthentication no/PasswordAuthentication yes/" /etc/ssh/sshd_config
    - systemctl restart sshd       # SSH 데몬 재시작

addons:
  - name: vpc-cni
    version: latest                 # 최신 버전의 vpc-cni 사용
    attachPolicyARNs:
      - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy

cloudWatch:
  clusterLogging:
    enableTypes: ["audit", "authenticator"] # 클러스터 로그 유형
