apiVersion: apps/v1
kind: Deployment
metadata:
  name: bungeecord
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bungeecord
  template:
    metadata:
      labels:
        app: bungeecord
    spec:
      containers:
      - name: bungeecord
        image: itzg/bungeecord:latest
        command: ["/bin/sh", "-c"]
        args:
        - >
          curl -f -o /server/BungeeCord-lastStableBuild.jar https://ci.md-5.net/job/BungeeCord/lastSuccessfulBuild/artifact/bootstrap/target/BungeeCord.jar &&
          java -jar /server/BungeeCord-lastStableBuild.jar -config /server/config.yml
        ports:
        - containerPort: 25577
        volumeMounts:
        - name: config-volume
          mountPath: /server/config.yml
          subPath: config.yml
      volumes:
      - name: config-volume
        configMap:
          name: bungeecord-config
---
apiVersion: v1
kind: Service
metadata:
  name: bungeecord-service
  namespace: default
spec:
  type: LoadBalancer
  ports:
  - port: 25577
    targetPort: 25577
  selector:
    app: bungeecord
