# server-1
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft-server-1
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minecraft-server-1
  template:
    metadata:
      labels:
        app: minecraft-server-1
    spec:
      containers:
      - name: minecraft-server-1
        image: itzg/minecraft-server
        env:
        - name: EULA
          value: "TRUE"
        - name: ONLINE_MODE
          value: "false" # online-mode 설정
        ports:
        - containerPort: 25565
        #0121 nfs이용한 백업 추가본
        volumeMounts:
        - name: server1-data
          mountPath: /data/world  # 월드 데이터 경로
      volumes:
      - name: server1-data
        persistentVolumeClaim:
          claimName: minecraft-server1-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: minecraft-service-1
  namespace: default
spec:
  type: NodePort
  ports:
  - port: 25565
    targetPort: 25565
    nodePort: 30001
  selector:
    app: minecraft-server-1