# server-2
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft-server-2
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minecraft-server-2
  template:
    metadata:
      labels:
        app: minecraft-server-2
    spec:
      containers:
      - name: minecraft-server-2
        image: itzg/minecraft-server
        env:
        - name: EULA
          value: "TRUE"
        - name: ONLINE_MODE
          value: "false" # online-mode 설정
        ports:
        - containerPort: 25565
        volumeMounts:
        - name: server2-data
          mountPath: /data/world  # 월드 데이터 경로
      volumes:
      - name: server2-data
        persistentVolumeClaim:
          claimName: ebs-pvc-2
apiVersion: v1
kind: Service
metadata:
  name: minecraft-service-2
  namespace: default
spec:
  type: NodePort
  ports:
  - port: 25565
    targetPort: 25565
    nodePort: 30002
  selector:
    app: minecraft-server-2