apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-ebs-pv-1                      # PV 이름
spec:
  capacity:
    storage: 20Gi                      # EBS 볼륨 크기
  volumeMode: Filesystem               # 파일 시스템 모드
  accessModes:
    - ReadWriteOnce                    # 단일 노드에서 읽기/쓰기 가능
  persistentVolumeReclaimPolicy: Retain # PVC 삭제 시 EBS 볼륨 유지
  storageClassName: manual             # StorageClass 이름 설정
  csi:
    driver: ebs.csi.aws.com            # EBS CSI 드라이버
    volumeHandle: vol-040957e38e82d386e # AWS EBS 볼륨 ID
    fsType: ext4                       # 파일 시스템 유형
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-ebs-pvc-1                     # PVC 이름
spec:
  accessModes:
    - ReadWriteOnce                    # 단일 노드에서 읽기/쓰기 가능
  resources:
    requests:
      storage: 20Gi                    # 요청한 스토리지 크기
  volumeName: my-ebs-pv-1                # 바인딩할 PV 이름
  storageClassName: manual             # StorageClass 이름 설정
