name: Deploy to EKS

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: ap-northeast-2
  CLUSTER_NAME: my-cluster

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. 코드 체크아웃
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. AWS CLI 설정 (OIDC 사용)
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        role-to-assume: arn:aws:iam::767397791112:role/GitHubActionsEKSRole
        aws-region: ${{ env.AWS_REGION }}

    # 3. EKS kubeconfig 업데이트
    - name: Update kubeconfig
      run: |
        aws eks update-kubeconfig --region ${{ env.AWS_REGION }} --name ${{ env.CLUSTER_NAME }}
    
    # EBS CSI 드라이버 설치
    - name: CSI driver install
      run: |
        kubectl apply -k "github.com/kubernetes-sigs/aws-ebs-csi-driver/deploy/kubernetes/overlays/stable/ecr/?ref=release-1.11"

    # 4. Kubernetes 배포
    - name: Deploy to EKS
      run: |
        kubectl apply -f k8s/storageclass.yaml
        kubectl apply -f k8s/PVC1.yaml
        kubectl apply -f k8s/PVC2.yaml
        kubectl apply -f k8s/minecraft1.yaml
        kubectl apply -f k8s/minecraft2.yaml
        kubectl create configmap bungeecord-config --from-file=./k8s/config.yml -n default
        kubectl apply -f k8s/bungeecord.yaml

    # 5. 배포 상태 확인
    - name: Verify Deployment
      timeout-minutes: 2  # 2분 제한
      run: |
        kubectl rollout status deployment/minecraft-server-1
        
